# -*- coding: utf-8 -*-
"""intro_to_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ql8z32zGeaTJgbPfhwIhgVaEJKQ0z6ru
"""

x = 5
print(x)

y = 7
z = 10
print(y)
print(z)

x = 5
y = 8
z = x * x + 1
y = z
print(y)

x = 26
type(x)

x = True
type(x)

x = 4.5
type(x)

z= "sumit"
type(z)

x = "sumit"
z = " rajpoot"
a = x + z
print(a)